ALTER TYPE "WalletTxType" ADD VALUE IF NOT EXISTS 'WITHDRAW';

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "paymentCardLast4" TEXT,
ADD COLUMN IF NOT EXISTS "paymentCardBrand" TEXT,
ADD COLUMN IF NOT EXISTS "paymentCardLinkedAt" TIMESTAMP(3);
